# Generated by Django 3.0 on 2019-12-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Pd',
        ),
    ]
