# Generated by Django 3.0 on 2019-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20191211_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonfiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='string', max_length=200)),
                ('bookname', models.CharField(default='string', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
