# Generated by Django 3.0 on 2019-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_biography_mysteries_romance'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='mysteries',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='nonfiction',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='pd',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='romance',
            name='text',
            field=models.TextField(default=True),
        ),
    ]
